### ISSUE TITLE
Options Menu

### ISSUE THREAD

**Issue by dwesolowski** [HexoMod/WorldEditCUI-Forge-Edition-3#1]
How do you open the options section to configure?
Using 1.15.2
Forge 31.2.0
CUI 3.0.3

**Comment by dwesolowski** [comment]
Sorry, found the options

**Comment by chaojian-zhang** [comment]
> Sorry, found the options

Can you please share your solution?

**Comment by dwesolowski** [comment]
Start the launcher> Optioins > Controls - scroll down to the keybinds for it.
