### ISSUE TITLE
Add support for other mods and plugins

### ISSUE THREAD

**Issue by PixelmonPRO** [HexoMod/WorldEditCUI-Forge-Edition-3#2]
Hello! I have been using the regular version WeCUI liteloader for a long time, and in some plugins its support was added for visualization, as an example of GriefPrevention (https://github.com/MinecraftPortCentral/GriefPrevention) / GriefDefender (https://github.com/bloodmc/GriefDefender).
After checking your mod, I realized that vialization stopped working. I initially asked the developer GriefDefender to add support for vialization with your mod, and received this answer: https://github.com/Mumfrey/WorldEditCUI/issues/16 `ForgeEdition dev needs to make the same changes as Mumfrey if he wants it to work.` https://github.com/mikroskeem/WorldEditCUI `He needs later version changes.`
Therefore, I ask you to add the latest changes, for the operation of the vialization of other mods / plugins, thanks in advance! :)

**Comment by hexosse** [comment]
I just read what has been discussed between bloodmc and Mumfrey in 2017.
this can be done without so many changes.

**Comment by LokeYourLord** [comment]
Would it also be possible for you to add support for RedProtect (https://ore.spongepowered.org/FabioZumbi12/RedProtect) on 1.12.2? That would be awesome since he also supports WECUI~

**Comment by hexosse** [comment]
@LokeYourLord I'll look into it. But can you open another issue for it?
Thanks
