### ISSUE TITLE
WorldEdit CUI 3 don't support bungeecord with some other mods installed

### ISSUE THREAD

**Issue by arturek1666** [HexoMod/WorldEditCUI-Forge-Edition-3#3]
Hi,

I had notice that if server is in bungeecord the selection will only work on the first server you join but not on the other servers in the same network, as example from lobby I am going to survival and in survival visualization don't work when selecting with worldedit. What strange is that when switched from survival to lobby the selection don't work there as well, so I have to leave the server and join to see visualization in the lobby.

Video Evidence of the issue:
https://streamable.com/iz3q60

Mc Version: 1.15.2
Spigot 1.15.2

**Comment by hexosse** [comment]
This is strange as it works for me.

Just to be sure I just created :
- bungee server
- lobby server with WorldEdit
- default server with WorldEdit

when I change from one server to another I don't have any problems.
As I can see on your video, on don't use default bungee command to change from one server to another. Which plugin do you use?

**Comment by arturek1666** [comment]
Hi, I am actually using waterfall (bungeecord fork)
My plugin on bungee:
![image](https://user-images.githubusercontent.com/1558228/82371987-0a889200-9a13-11ea-8a2e-0a99179c4564.png)

I will do more tests, on my local device, just to see exactly what is going on, will update this message soon.

**Comment by arturek1666** [comment]
Ok I will update again, looks like one of the mods I had is making that issue.

**Comment by arturek1666** [comment]
Looks like I had fine one that has issues with is optifine, but there is another mod that is casuing an issue what is strange is that if:
This list of mods are together it works:
![image](https://user-images.githubusercontent.com/1558228/82379692-44f82c00-9a1f-11ea-8c08-49723bd7151e.png)
If I have this mods it also works:
![image](https://user-images.githubusercontent.com/1558228/82379817-796be800-9a1f-11ea-8825-9ee0faf206ba.png)
Hover if I merge all mods from this list (not including optifine) it will not work.

How strange is that lol

**Comment by hexosse** [comment]
Did you manage to find which mod could cause the problem?

**Comment by arturek1666** [comment]
The one that for sure has issues is optifine that's one, with the rest it fills like it's more like a combinations of the mods. So it's hard to detect, however try to reproduce the issue just with your plugin and optifine and having bungee sever. and 2 sub servers.

**Comment by arturek1666** [comment]
Old issue mostly resolved.
