### ISSUE TITLE
CurseForge Link in Readme is wrong

### ISSUE THREAD

**Issue by TFaehrmann** [HexoMod/WorldEditCUI-Forge-Edition-3#7]
Hey,

Did you remove the mod from CurseForge or ist the Link in the Readme wrong ?
I diddn't found WorldEditCUI-Forge-Edition-3 specific version downloads (except the master repository :b)

**Comment by TFaehrmann** [comment]
Yep the link in the Readme is only not right

Right link:
https://www.curseforge.com/minecraft/mc-mods/worldeditcui-forge-edition-3/files

**Comment by hexosse** [comment]
I have updated the readme file.
Thanks
