### ISSUE TITLE
Add support for new version

### ISSUE THREAD

**Issue by Nik-ADA** [HexoMod/WorldEditCUI-Forge-Edition-3#8]
Add support for new version mincraft 1.16.1

**Comment by hexosse** [comment]
I’m working on the 1.16.2 update

**Comment by hexosse** [comment]
Version 3.0.6 add support to 1.16.2

see [https://www.curseforge.com/minecraft/mc-mods/worldeditcui-forge-edition-3/files](https://www.curseforge.com/minecraft/mc-mods/worldeditcui-forge-edition-3/files)
